from __future__ import annotations

from pathlib import Path
import matplotlib.pyplot as plt
from .schemas import MatchData, FigureMeta

def render_match_timeline(match: MatchData, out_path: Path) -> FigureMeta:
    """Render a vertical timeline of key match events."""
    fig, ax = plt.subplots(figsize=(12, 16), facecolor='#1e7a46')
    ax.set_facecolor('#1e7a46')
    
    # Hide axes
    ax.get_xaxis().set_visible(False)
    ax.get_yaxis().set_visible(False)
    for spine in ax.spines.values():
        spine.set_visible(False)

    # Central line
    ax.axvline(x=0.5, color='white', linewidth=2, zorder=1)
    
    events = match.timeline
    if not events:
        # Placeholder text if no events
        ax.text(0.5, 0.5, "No key events recorded", color='white', ha='center', fontsize=20)
    else:
        # Normalize time for vertical positioning (0 to 1)
        max_min = max(90, max(e.minute for e in events))
        
        home_team_id = next(t.id for t in match.teams if t.side == "home")
        
        for event in events:
            y = 1 - (event.minute / (max_min + 5))
            side = 1 if event.teamId == home_team_id else -1
            
            # Marker on the timeline
            color = "#fbbf24" if event.type == "goal" else "white"
            ax.scatter(0.5, y, s=200, color=color, edgecolor='white', zorder=3)
            
            # Label
            x_pos = 0.5 + (side * 0.05)
            ha = 'left' if side == 1 else 'right'
            
            # Event icon/type emoji-like text
            icons = {"goal": "⚽", "card": "🟨", "subst": "🔄", "var": "🖥️"}
            icon = icons.get(event.type, "•")
            if "Red Card" in event.detail: icon = "🟥"
            
            text = f"{event.minute}' {icon} {event.playerName}\n{event.detail}"
            ax.text(x_pos, y, text, color='white', ha=ha, va='center', 
                    fontsize=12, fontweight='bold',
                    bbox=dict(facecolor='#1e7a46', edgecolor='white', alpha=0.6, boxstyle='round,pad=0.5'))

    # Title
    title = f"Match Timeline: {match.match.homeTeam} vs {match.match.awayTeam}"
    ax.text(0.5, 1.05, title, color='white', fontsize=20, fontweight='bold', ha='center', transform=ax.transAxes)
    
    # Footnote
    ax.text(0.5, -0.05, "Generated by GoalGazer Analytics", color='white', alpha=0.5, ha='center', transform=ax.transAxes)

    plt.tight_layout()
    out_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out_path, dpi=200, facecolor='#1e7a46')
    plt.close(fig)

    return FigureMeta(
        src_relative=str(out_path).split("public")[1].replace("\\", "/"),
        alt=f"Vertical timeline of match events for {match.match.homeTeam} vs {match.match.awayTeam}.",
        caption="Match timeline showing goals, cards, and substitutions.",
        width=1200,
        height=1600,
    )
